"use client";
import { useState,useEffect,useRef } from "react";
import { toast } from "sonner";
import { careerApi,defaultPreferences,normalizeJob,applicationOutcome,type Job,type Preferences } from "./career";
export function useCareer(){
 const [connection,setConnection]=useState<{connected:boolean;configured:boolean;local?:boolean;message:string}>({connected:false,configured:false,message:"Checking your agent connection…"});
 const [runBusy,setRunBusy]=useState("");
 const [jobs,setJobs]=useState<Job[]>([]); const [profile,setProfile]=useState<Record<string,unknown>|null>(null);
 const [preferences,setPreferences]=useState<Preferences>(defaultPreferences);const [busy,setBusy]=useState("");const [events,setEvents]=useState<string[]>([]);const stop=useRef(false);const running=useRef(false);
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem("career-pilot-preferences")||"null");if(p&&typeof p.roles==="string")setPreferences({...defaultPreferences,...p});}catch{}void check();},[]);
 useEffect(()=>{if(!connection.local)return;let mounted=true;let pending=false;let previous="";
 const poll=async()=>{if(pending)return;pending=true;try{const d=await careerApi("runs/current");if(!mounted)return;const active=["running","pausing"].includes(String(d.status));setRunBusy(active?String(d.message):"");setEvents(Array.isArray(d.events)?d.events as string[]:[]);if(previous&&previous!==String(d.status)&&!active)await refresh();previous=String(d.status);}catch{}finally{pending=false;}};
 void poll();const timer=setInterval(poll,2000);return()=>{mounted=false;clearInterval(timer);};},[connection.local]);
 function savePreferences(p:Preferences){const next={...p,experience:Math.max(0,Math.min(50,Number(p.experience)||0)),minMatch:Math.max(70,Math.min(100,Number(p.minMatch)||85)),limit:Math.max(1,Math.min(20,Number(p.limit)||5))};setPreferences(next);try{localStorage.setItem("career-pilot-preferences",JSON.stringify(next));}catch{}toast.success("Preferences saved on this device.");}
 async function refresh(){const [a,p]=await Promise.all([careerApi("applications"),careerApi("profile")]);const next=(Array.isArray(a)?a:[]).map(normalizeJob);setJobs(next);setProfile(p.json_exists||p.parsed_preview?p:null);return next;}
 async function check(){try{const state=await careerApi("status");setConnection(state);if(state.connected)await refresh();return state.connected;}catch(e){setConnection({connected:false,configured:false,message:(e as Error).message});return false;}}
 function log(message:string){setEvents(a=>[message,...a].slice(0,30));}
 async function act<T>(label:string,fn:()=>Promise<T>):Promise<T|undefined>{if(running.current||runBusy){toast.info("Wait for the current action to finish.");return;}running.current=true;setBusy(label);try{return await fn();}catch(e){toast.error((e as Error).message);log((e as Error).message);}finally{running.current=false;setBusy("");}}
 async function search(){if(!preferences.roles.trim())throw new Error("Add at least one target role in your preferences.");await careerApi("jobs/search",{queries:preferences.roles.split(",").map(s=>s.trim()).filter(Boolean),location:preferences.location,experience:preferences.experience,pages:1,job_age:7});return refresh();}
 async function run(){if(connection.local){await act("Starting agent…",async()=>{const d=await careerApi("runs/start",preferences);setRunBusy(String(d.message));});return;}await act("Finding your next move…",async()=>{stop.current=false;log("Searching for roles using your preferences.");const all=await search();const eligible=all.filter(j=>j.status==="PENDING"&&j.recommendation==="APPLY"&&j.match>=preferences.minMatch&&(j.eligibility||0)>=preferences.minMatch).sort((a,b)=>b.match-a.match).slice(0,preferences.limit);log(`Found ${all.length} opportunities; ${eligible.length} meet your application rules.`);for(const job of eligible){if(stop.current)break;setBusy(`${preferences.autoApply?"Applying to":"Preparing"} ${job.company}…`);try{const data=await careerApi(`applications/${encodeURIComponent(job.id)}/${preferences.autoApply?"auto-apply":"tailor"}`,{});const status=preferences.autoApply?applicationOutcome(data):"PREPARED";setJobs(a=>a.map(j=>j.id===job.id?{...j,status,...(!preferences.autoApply?{summary:data.tailored_summary,tags:data.tailored_skills||[],ats:data.ats_score}:{})}:j));log(`${job.company}: ${status==="APPLIED"?"submission confirmed":status==="PREPARED"?"prepared for review":String(data.detail||"needs your attention")}.`);}catch(e){log(`${job.company}: ${(e as Error).message}`);setJobs(a=>a.map(j=>j.id===job.id?{...j,status:"NEEDS_REVIEW"}:j));}}
 log(stop.current?"Agent stopped after the current action.":"This agent run is complete.");toast.success(stop.current?"Agent paused.":"Agent run complete. Review the results in Applications.");});}
 async function jobAction(job:Job,action:string){await act(`Working on ${job.company}…`,async()=>{const result=await careerApi(`applications/${encodeURIComponent(job.id)}/${action}`,{});if(action==="auto-apply"){const status=applicationOutcome(result);setJobs(a=>a.map(j=>j.id===job.id?{...j,status,message:result.detail}:j));log(`${job.company}: ${status.toLowerCase().replaceAll("_"," ")}.`);toast.info(status==="APPLIED"?"Submission confirmed.":"Review the agent’s result before continuing.");}else{setJobs(a=>a.map(j=>j.id===job.id?normalizeJob(result):j));toast.success(action==="tailor"?"Tailored resume is ready.":"Application updated.");}});}
 return {connection,jobs,profile,preferences,busy:busy||runBusy,events,check,refresh,setProfile,savePreferences,run,act,jobAction,search,stop:()=>{if(connection.local){void careerApi("runs/pause",{}).catch(e=>toast.error(e.message));return;}stop.current=true;log("Pause requested. Finishing the current action first.");}};
}
