"use client";
import { useState } from "react";
import { Bot,FileText,Upload,Check,ArrowRight,RefreshCw,ShieldCheck,Settings2,Play,Pause,Search,ExternalLink,Download,AlertCircle } from "lucide-react";
import { Switch } from "@/components/ui/switch";
import { Slider } from "@/components/ui/slider";
import { Alert,AlertDescription } from "@/components/ui/alert";
import { Table,TableHeader,TableHead,TableRow,TableBody,TableCell } from "@/components/ui/table";
import { careerApi,localResume,type Job } from "@/lib/career";
import { useCareer } from "@/lib/use-career";
import { toast } from "sonner";
type Career=ReturnType<typeof useCareer>;
export function PreferencesForm({career,onDone}:{career:Career;onDone:()=>void}){
 const [draft,setDraft]=useState(career.preferences);
 return <form className="workflow-form" onSubmit={e=>{e.preventDefault();career.savePreferences(draft);onDone();}}><label>Target roles<input required value={draft.roles} onChange={e=>setDraft({...draft,roles:e.target.value})} placeholder="Software Engineer, Product Engineer"/><small>Separate multiple roles with commas.</small></label><div className="field-pair"><label>Location<input value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})} placeholder="Any location"/></label><label>Years of experience<input type="number" min="0" max="50" required value={draft.experience} onChange={e=>setDraft({...draft,experience:Number(e.target.value)})}/></label></div><label htmlFor="match-slider">Minimum match <strong>{draft.minMatch}%</strong></label><Slider id="match-slider" aria-label="Minimum match percentage" min={70} max={100} step={1} value={[draft.minMatch]} onValueChange={v=>setDraft({...draft,minMatch:v[0]})}/><label>Applications per run<input type="number" min="1" max="20" required value={draft.limit} onChange={e=>setDraft({...draft,limit:Number(e.target.value)})}/></label><div className="switch-row"><div><label htmlFor="auto-apply">Automatically submit eligible applications</label><p>Off: prepare tailored resumes for review. On: send applications to eligible roles during a run.</p></div><Switch id="auto-apply" checked={draft.autoApply} onCheckedChange={v=>setDraft({...draft,autoApply:v})}/></div>{draft.autoApply&&<Alert><ShieldCheck/><AlertDescription>Your agent will share your resume with matching employers. Only roles meeting both match and eligibility thresholds are included. Questions it cannot answer need your review.</AlertDescription></Alert>}<button className="primary" type="submit">Save preferences <Check size={16}/></button></form>;
}
function skillLabels(value:unknown):string[]{return Array.isArray(value)?value.map(s=>typeof s==="string"?s:typeof s==="object"&&s!==null?String((s as {name?:string;skill?:string}).name||(s as {skill?:string}).skill||""):"").filter(Boolean):[];}
export function ResumeFlow({career,onDone}:{career:Career;onDone:()=>void}){
 const [file,setFile]=useState<File|null>(null);const [facts,setFacts]=useState<Record<string,unknown>|null>(null);const [error,setError]=useState("");const [working,setWorking]=useState(false);
 async function parse(){if(!file)return;setWorking(true);setError("");try{if(career.connection.connected){const form=new FormData();form.append("resume_file",file);const data=await careerApi("profile/parse",form);setFacts(data.facts);}else if(file.name.toLowerCase().endsWith(".txt")){setFacts(localResume(await file.text()));}else{throw new Error("Your file is ready. Connect the agent to read PDF and Word resumes, or use a TXT file to try local text extraction.");}}catch(e){setError((e as Error).message);}finally{setWorking(false);}}
 async function save(){setWorking(true);setError("");try{if(career.connection.connected){await careerApi("profile/store",{});await career.refresh();toast.success("Your profile is ready for job matching.");}else{career.setProfile({name:facts?.name,skills_count:skillLabels(facts?.skills).length,source_resume:file?.name,preview:facts,local_only:true,complete:false});toast.success("Resume preview added for this session. Connect your agent for live matching.");}onDone();}catch(e){setError((e as Error).message);}finally{setWorking(false);}}
 function choose(f:File|null){setError("");setFacts(null);setFile(null);if(!f)return;if(f.size>10*1024*1024){setError("Choose a file smaller than 10 MB.");return;}if(!/\.(pdf|docx|txt)$/i.test(f.name)){setError("Choose a PDF, DOCX, or TXT file.");return;}setFile(f);}
 return <div className="workflow-form">{!facts?<><label className="upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0]||null);}}><Upload size={29}/><strong>{file?file.name:"Choose or drop your resume"}</strong><span>PDF, DOCX, or TXT · Up to 10 MB</span><input type="file" aria-label="Choose resume file" accept=".pdf,.docx,.txt" disabled={working} onChange={e=>choose(e.target.files?.[0]||null)}/></label><p className="form-help">{career.connection.connected?"Your resume will be sent to your connected Career Pilot agent. Review the extracted facts before saving.":"TXT previews stay in this tab. PDF and Word parsing requires a connected agent. No applications will be sent in demo mode."}</p><button className="primary" disabled={!file||working||!!career.busy} onClick={parse}>{working?"Reading your resume…":"Read my resume"}<ArrowRight size={16}/></button></>:<><div className="success-callout"><Check size={18}/> Ready for your review</div><div className="resume-facts"><small>DETECTED NAME</small><h3>{String(facts.name||"Name not detected")}</h3>{facts.email!=null&&<p>{String(facts.email)}</p>}<small>DETECTED SKILLS</small><div className="tags">{skillLabels(facts.skills).length?skillLabels(facts.skills).map(s=><span key={s}>{s}</span>):<p>No skills detected. Check your source resume.</p>}</div>{facts.summary!=null&&<p>{String(facts.summary)}</p>}</div><details><summary>Review all extracted details</summary><pre className="facts-json">{JSON.stringify(facts,null,2)}</pre></details><p className="form-help">Check these facts against your resume. If anything is incorrect, update your source file and upload it again.</p><button className="primary" disabled={working} onClick={save}>{working?"Saving…":career.connection.connected?"Use this profile":"Use session preview"}<Check size={16}/></button><button className="text-button" disabled={working} onClick={()=>{setFacts(null);setFile(null)}}>Choose another file</button></>}{error&&<p className="form-error" role="alert"><AlertCircle size={16}/>{error}</p>}</div>;
}
export function ConnectionPanel({career,onPreferences}:{career:Career;onPreferences:()=>void}){
 const [checking,setChecking]=useState(false);
 const ready=career.connection.connected;
 return <div className="workflow-form"><div className={`connection-status ${ready?"connected":""}`}><Bot size={24}/><div><strong>{ready?"Your agent is connected":"Let’s connect your agent"}</strong><p>{career.connection.message}</p></div></div><ol className="setup-steps"><li><span>1</span><div><strong>Connect Career Pilot</strong><p>Your private agent powers resume analysis, job discovery, and applications.</p></div></li><li><span>2</span><div><strong>Add your model and job account</strong><p>Configure a chat model and your Naukri account on your agent.</p></div></li><li><span>3</span><div><strong>Choose how your agent applies</strong><p>Prepare for review or submit eligible applications automatically.</p></div></li></ol><div className="button-row"><button className="primary" disabled={checking||!!career.busy} onClick={async()=>{setChecking(true);const ok=await career.check();setChecking(false);toast[ok?"success":"info"](ok?"Agent connected.":"Your agent is not available yet.");}}><RefreshCw size={16} className={checking?"spin":""}/>{checking?"Checking…":"Check connection"}</button><button className="secondary" onClick={onPreferences}><Settings2 size={16}/>Preferences</button></div><a className="setup-link" href="/setup.md" target="_blank" rel="noreferrer">Open the connection guide <ExternalLink size={14}/></a></div>;
}
export function AgentSettings({career,onConnect,onPreferences}:{career:Career;onConnect:()=>void;onPreferences:()=>void}){
 return <div className="settings-grid"><section className="settings-panel"><div className="section-heading"><h2>Your agent, your rules</h2><Bot size={22}/></div><div className="setting-line"><span>Connection</span><strong>{career.connection.connected?"Connected":"Not connected"}</strong></div><div className="setting-line"><span>Application mode</span><strong>{career.preferences.autoApply?"Automatic submission":"Prepare for review"}</strong></div><div className="setting-line"><span>Minimum match & eligibility</span><strong>{career.preferences.minMatch}%</strong></div><div className="setting-line"><span>Maximum per run</span><strong>{career.preferences.limit} applications</strong></div><div className="setting-line"><span>Target roles</span><strong>{career.preferences.roles}</strong></div><p className="form-help">A run discovers jobs, checks fit, and processes eligible applications. Keep this tab open until the run finishes. Pausing takes effect after the current action.</p><div className="button-row"><button className="secondary" onClick={onPreferences}><Settings2 size={16}/> Edit preferences</button>{career.busy?<button className="primary" onClick={career.stop}><Pause size={16}/>Pause after current</button>:<button className="primary" onClick={career.connection.connected?career.run:onConnect}><Play size={16}/>{career.connection.connected?"Run agent":"Connect agent"}</button>}</div>{career.busy&&<div role="status" className="run-status"><RefreshCw size={16} className="spin"/>{career.busy}</div>}</section><section className="settings-panel"><h2>Run activity</h2>{career.events.length?<ol className="event-log">{career.events.map((e,i)=><li key={i}>{e}</li>)}</ol>:<div className="empty-state compact"><RadioIcon/><p>When your agent runs, each step and outcome will appear here.</p></div>}</section></div>;
}
const RadioIcon=()=> <Bot size={30}/>;
export function ApplicationList({career,onSelect,onConnect}:{career:Career;onSelect:(j:Job)=>void;onConnect:()=>void}){
 const [filter,setFilter]=useState("");
 const rows=career.jobs.filter(j=>`${j.title} ${j.company} ${j.status}`.toLowerCase().includes(filter.toLowerCase()));
 if(!career.connection.connected)return <section className="panel empty-state"><BriefcaseIcon/><h2>Your next chapter, tracked.</h2><p>Connect your agent to see real applications and their outcomes here. Sample jobs are never submitted.</p><button className="primary" onClick={onConnect}>Connect agent <ArrowRight size={16}/></button></section>;
 return <section className="settings-panel applications-panel"><div className="section-heading"><h2>Your application pipeline</h2><button disabled={!!career.busy} className="text-button" onClick={()=>career.act("Refreshing applications…",career.refresh)}><RefreshCw size={15}/>Refresh</button></div><div className="search-input"><Search size={18}/><input aria-label="Search applications" placeholder="Search company, role, or status" value={filter} onChange={e=>setFilter(e.target.value)}/></div>{rows.length?<Table><TableHeader><TableRow><TableHead>Opportunity</TableHead><TableHead>Match</TableHead><TableHead>Status</TableHead><TableHead>Details</TableHead></TableRow></TableHeader><TableBody>{rows.map(j=><TableRow key={j.id}><TableCell><strong>{j.title}</strong><small className="company-name">{j.company}</small></TableCell><TableCell>{j.match}%</TableCell><TableCell><span className={`status-badge ${j.status?.toLowerCase()}`}>{j.status?.replaceAll("_"," ").toLowerCase()}</span></TableCell><TableCell><button className="text-button" onClick={()=>onSelect(j)}>Review <ArrowRight size={14}/></button></TableCell></TableRow>)}</TableBody></Table>:<div className="empty-state compact"><Search size={28}/><p>{filter?"No applications match this search.":"Run your agent to find your first matching opportunities."}</p></div>}</section>;
}
const BriefcaseIcon=()=> <FileText size={38}/>;
export function JobDetails({job,career,onConnect}:{job:Job;career:Career;onConnect:()=>void}){
 const sample=job.id.startsWith("sample-");
 const current=career.jobs.find(j=>j.id===job.id)||job;
 return <div className="workflow-form"><div className="match-summary"><Check size={20}/>{job.match}% {sample?"sample match":"resume match"}</div>{sample?<p>Sample opportunity for exploring the workspace. Connect your agent for current listings and matches based on your resume.</p>:<><div className="job-meta"><span>{job.location}</span><span>{current.status?.replaceAll("_"," ")}</span>{current.ats!=null&&<span>ATS score: {current.ats}%</span>}</div><div><h3>Why this role fits</h3><ul className="detail-list">{(job.reasons?.length?job.reasons:["Detailed match reasons have not been provided by the agent."]).map(s=><li key={s}>{s}</li>)}</ul></div>{!!job.missing?.length&&<div><h3>Things to review</h3><ul className="detail-list">{job.missing.map(s=><li key={s}>{s}</li>)}</ul></div>}{current.summary&&<div className="resume-facts"><h3>Your tailored summary</h3><p>{current.summary}</p></div>}{current.message&&<p className="form-help">{current.message}</p>}</>}<div className="tags">{current.tags.map(t=><span key={t}>{t}</span>)}</div>{sample?<button className="primary" onClick={onConnect}>Connect to discover real jobs <ArrowRight size={16}/></button>:<><div className="button-row"><button className="secondary" disabled={!!career.busy} onClick={()=>career.jobAction(current,"tailor")}><FileText size={16}/> Tailor resume</button>{current.summary&&<a className="secondary" href={`/api/career/applications/${encodeURIComponent(job.id)}/resume-file`} download><Download size={16}/> Download</a>}{job.url&&<a className="text-button" href={job.url} target="_blank" rel="noreferrer">View listing <ExternalLink size={14}/></a>}</div>{["PENDING","PREPARED","NEEDS_REVIEW","FAILED"].includes(current.status||"")&&<button className="primary" disabled={!!career.busy||current.recommendation!=="APPLY"||current.match<career.preferences.minMatch||(current.eligibility||0)<career.preferences.minMatch} onClick={()=>career.jobAction(current,"auto-apply")}>{career.busy||"Apply to this role"}<ArrowRight size={16}/></button>}{current.status==="APPLIED"&&<button className="secondary" disabled={!!career.busy} onClick={()=>career.jobAction(current,"interview")}>Mark interview received</button>}{current.status==="INTERVIEW"&&<button className="secondary" disabled={!!career.busy} onClick={()=>career.jobAction(current,"offer")}>Mark offer received</button>}<p className="form-help">Applying shares your resume with this employer. Your agent pauses on blocked steps or questions requiring your input.</p></>}</div>;
}
